name: Update EDK2 on Release and Create Tag & Release

on:
  schedule:
    # 每天检查一次是否有新Release（UTC时间午夜）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      has_new_release: ${{ steps.check_release.outputs.has_new_release }}
      latest_tag: ${{ steps.check_release.outputs.latest_tag }}
      latest_sha: ${{ steps.check_release.outputs.latest_sha }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for new EDK2 releases
      id: check_release
      uses: actions/github-script@v6
      with:
        script: |
          try {
            // 获取tianocore/edk2的最新release
            const { data: latestRelease } = await github.rest.repos.getLatestRelease({
              owner: 'tianocore',
              repo: 'edk2'
            });
            
            // 获取当前submodule的版本
            const currentSubmoduleSha = require('child_process').execSync('cd edk2 && git rev-parse HEAD').toString().trim();
            
            // 获取最新release对应的commit SHA
            const latestReleaseSha = await github.rest.repos.getCommit({
              owner: 'tianocore',
              repo: 'edk2',
              ref: latestRelease.tag_name
            }).then(response => response.data.sha);
            
            console.log(`Current submodule SHA: ${currentSubmoduleSha}`);
            console.log(`Latest release SHA: ${latestReleaseSha}`);
            console.log(`Latest release tag: ${latestRelease.tag_name}`);
            
            // 比较SHA是否相同
            if (currentSubmoduleSha !== latestReleaseSha) {
              console.log('New release detected!');
              core.setOutput('has_new_release', 'true');
              core.setOutput('latest_tag', latestRelease.tag_name);
              core.setOutput('latest_sha', latestReleaseSha);
            } else {
              console.log('No new release detected.');
              core.setOutput('has_new_release', 'false');
            }
          } catch (error) {
            console.error('Error checking for releases:', error.message);
            core.setOutput('has_new_release', 'false');
          }

  update-submodule:
    needs: check-release
    if: needs.check-release.outputs.has_new_release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write # 需要写入权限来创建标签和发布Release
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current year and count existing tags
      id: tag_info
      run: |
        # 获取当前年份的后两位
        CURRENT_YEAR=$(date +%y)
        echo "current_year=$CURRENT_YEAR" >> $GITHUB_OUTPUT
        
        # 统计今年已有的H标签数量
        EXISTING_TAGS=$(git tag -l "${CURRENT_YEAR}H*" | wc -l)
        echo "existing_tags=$EXISTING_TAGS" >> $GITHUB_OUTPUT
        
        # 计算新标签号
        NEW_TAG_NUMBER=$((EXISTING_TAGS + 1))
        echo "new_tag_number=$NEW_TAG_NUMBER" >> $GITHUB_OUTPUT
        
        # 构建完整标签名
        NEW_TAG="${CURRENT_YEAR}H${NEW_TAG_NUMBER}"
        echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
        
        echo "新标签将是: $NEW_TAG"

    - name: Record release version
      run: |
        echo "更新到 EDK2 发布版本: ${{ needs.check-release.outputs.latest_tag }}"
        echo "发布版本 SHA: ${{ needs.check-release.outputs.latest_sha }}"

    - name: Update EDK2 submodule to latest release
      run: |
        # 进入EDK2 submodule目录
        cd edk2
        
        # 获取所有标签和提交
        git fetch https://github.com/tianocore/edk2.git --tags --force
        
        # 明确切换到release对应的确切commit
        git checkout ${{ needs.check-release.outputs.latest_sha }} --force
        
        # 递归更新所有嵌套的submodule
        echo "开始递归更新EDK2的嵌套submodule..."
        git submodule update --init --recursive --force
        
        # 返回主仓库目录
        cd ..
        
        # 添加更新后的submodule
        git add edk2
        
        # 提交更新
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "chore: update EDK2 submodule to release ${{ needs.check-release.outputs.latest_tag }}"
        
        # 创建标签
        git tag ${{ steps.tag_info.outputs.new_tag }}
        
        # 推送更改和标签
        git push origin main
        git push origin ${{ steps.tag_info.outputs.new_tag }}
        
        echo "已更新EDK2 submodule到发布版本 ${{ needs.check-release.outputs.latest_tag }}，并创建标签 ${{ steps.tag_info.outputs.new_tag }}"

    - name: Verify submodule is at correct commit
      run: |
        cd edk2
        CURRENT_SHA=$(git rev-parse HEAD)
        EXPECTED_SHA="${{ needs.check-release.outputs.latest_sha }}"
        if [ "$CURRENT_SHA" != "$EXPECTED_SHA" ]; then
          echo "错误: Submodule没有在预期的commit上!"
          echo "当前: $CURRENT_SHA"
          echo "预期: $EXPECTED_SHA"
          exit 1
        else
          echo "验证成功: Submodule已正确更新到预期commit"
        fi

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_info.outputs.new_tag }}
        name: Release ${{ steps.tag_info.outputs.new_tag }}
        body: |
          ## 更新内容
          
          此版本更新了 EDK2 submodule 到上游发布版本 [${{ needs.check-release.outputs.latest_tag }}](https://github.com/tianocore/edk2/releases/tag/${{ needs.check-release.outputs.latest_tag }})
          
          ### EDK2 更新详情
          - **版本**: ${{ needs.check-release.outputs.latest_tag }}
          - **Commit SHA**: ${{ needs.check-release.outputs.latest_sha }}
          - **更新日期**: ${{ steps.tag_info.outputs.current_date }}
          
          ### 自动生成信息
          此 Release 由 GitHub Actions 自动创建，基于上游 EDK2 的新发布版本。
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Notify on update
      run: |
        echo "EDK2 submodule及其所有嵌套submodule已更新到发布版本 ${{ needs.check-release.outputs.latest_tag }}"
        echo "已创建标签 ${{ steps.tag_info.outputs.new_tag }} 并发布 Release"
